### ISSUE TITLE
TensorFlow failing on Ubuntu

### ISSUE THREAD

**Issue by meteorcloudy** [bazelbuild/continuous-integration#305]
https://buildkite.com/bazel/tensorflow/builds/1067#629ff53d-4828-418a-9903-f96b409d0262

Error message:
```
ImportError: No module named keras_applications
```

Can you run `pip install keras_applications` on the Ubuntu machines to fix this issue?
@philwo @buchgr

**Comment by philwo** [comment]
@meteorcloudy Only on Ubuntu, or also on macOS and Windows?

**Comment by superying** [comment]
The same problem when I bazel build the latest tensorflow source code on Ubuntu.
And running pip install keras_applications fixed this issue.

**Comment by tsell** [comment]
+1 I see the same issue on MacOS High Sierra 10.13.6, following the macos instructions here: https://www.tensorflow.org/install/install_sources#PrepareMac

Running `pip install keras_applications` fixed it.

**Comment by philwo** [comment]
@meteorcloudy This should be fixed with the new CI images. Could you please verify and close? :)

**Comment by meteorcloudy** [comment]
@philwo It's now fixed on Ubuntu 16.04, but still failing on 14.04, should we just remove 14.04 for TensorFlow?

**Comment by philwo** [comment]
@meteorcloudy Yes, unfortunately I can't install it on our Ubuntu 14.04 VMs, because the keras_* packages depend on newer versions of many big packages like NumPy, which aren't shipped by that old version of Ubuntu. We would have to use something like virtualenv to setup an environment with the correct packages completely installed via pip just for TF.

If it's OK for you, I would recommend to just not test TensorFlow on Ubuntu 14.04. 😊

**Comment by meteorcloudy** [comment]
On the [Linux page](https://www.tensorflow.org/install/install_linux) of TensorFlow official site, it says:
> This guide explains how to install TensorFlow on Ubuntu Linux. While these instructions may work on other Linux variants, they are tested and supported with the following system requirements:

> 64-bit desktops or laptops
> Ubuntu 16.04 or higher

I think it's OK to remove 14.04 on our CI ;)
